### ISSUE TITLE
Scoreboard Lines Randomizing

### ISSUE THREAD

**Issue by Ixf1nity** [ThatKawaiiSam/Assemble#11]
My Scoreboard lines are randomizing and changing.

Video:

https://user-images.githubusercontent.com/97213130/161421304-ab1d947e-e65a-44b5-b11b-0b4b975c84d0.mp4

Code:
![image](https://user-images.githubusercontent.com/97213130/161421391-c47f99b7-f08a-4317-8021-2445c3eddaba.png)

I tried with not using TextUtils or stuff but same issue ;( Please help

**Comment by hardcorefactions** [comment]
Can you send your YAML?

**Comment by SammySergi** [comment]
I would try logging the result of the lines you are trying to return, its either a mismatch in there, or you are using another Scoreboard/Tablist system that is conflicting with Assembles team system in some way.

**Comment by Ixf1nity** [comment]
@znotdeev @ThatKawaiiSam 
Thanks for reaching back, It's been over a year since I made this issue; so providing support right now is pointless. You shall not waste your time here, Thanks.
