### ISSUE TITLE
Implementing With Maven

### ISSUE THREAD

**Issue by Cony1407** [ThatKawaiiSam/Assemble#5]
How can i implements this with maven?

**Comment by sh1ry** [comment]
I made my own maven fork for this API, you can find it here: https://github.com/ShiryuDev/Assemble-Maven

**Comment by SammySergi** [comment]
I will setup a GitHub package so you can use locally without installing it on your system.

**Comment by SammySergi** [comment]
@Cony1407 there you go: https://github.com/ThatKawaiiSam/Assemble/packages/405008
