### ISSUE TITLE
Maven help

### ISSUE THREAD

**Issue by MrMcyeet** [ThatKawaiiSam/Assemble#7]
Im almost positive that this is something that im messing up, but when i try to add this to my project with
```
		<dependency>
			<groupId>io.github.thatkawaiisam</groupId>
			<artifactId>assemble</artifactId>
			<version>1.0-SNAPSHOT</version>
		</dependency>
```
it says
```
 Could not resolve dependencies for project group:Plugin:jar:1.0.0-SNAPSHOT: Failure to find io.github.thatkawaiisam:assemble:jar:1.0-SNAPSHOT in https://jitpack.io was cached in the local repository, resolution will not be reattempted until the update interval of jitpack.io has elapsed or updates are forced
```
Any suggestions or help?

**Comment by RaphaelWoude** [comment]
If the provided maven dependency doesn't work, use jitpack: https://jitpack.io/
Just enter the github url, choose a commit and jitpack will give you the correct dependency to use.

**Comment by MrMcyeet** [comment]
> If the provided maven dependency doesn't work, use jitpack: https://jitpack.io/
> Just enter the github url, choose a commit and jitpack will give you the correct dependency to use.

Hey thx, that worked <3
